# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkssl < Formula
  desc "Simple tool to check or monitor TLS/SSL certificates are working."
  homepage "https://www.checkssl.org/"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.0/checkssl_0.5.0_Darwin_arm64.tar.gz"
      sha256 "9b763646d06441ee553d2aaf7d10f0b2b6de5372c998a73b30bd484fb7705a2b"

      def install
        bin.install "checkssl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.0/checkssl_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "be3611639e732ae285a10375f160ae778e05f836c0546bd9dcc5dcaea3764dbe"

      def install
        bin.install "checkssl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.0/checkssl_0.5.0_Linux_arm64.tar.gz"
      sha256 "3fe6d73d93b94268a62616520cb9ef498e1cbccc482a10b7bab028a1dff54a78"

      def install
        bin.install "checkssl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.0/checkssl_0.5.0_Linux_x86_64.tar.gz"
      sha256 "195ebe60be84053fd912d1d67751ae96b1307a2f2cc5f33905a90a6fb2a17579"

      def install
        bin.install "checkssl"
      end
    end
  end

  test do
    system "#{bin}/checkssl checkssl.org"
  end
end
