# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkssl < Formula
  desc "Simple tool to check or monitor TLS/SSL certificates are working."
  homepage "https://www.checkssl.org/"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.1/checkssl_Darwin_x86_64.tar.gz"
      sha256 "74620240ce26c6b3f5101493b3086ebfbe36da907f39f27055d5f0dc8f8fda06"

      def install
        bin.install "checkssl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.1/checkssl_Darwin_arm64.tar.gz"
      sha256 "1794a615b5905824b1396ca1ad1d1ec5a8d4134e736950a9cecd4dc5e5171d38"

      def install
        bin.install "checkssl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.1/checkssl_Linux_x86_64.tar.gz"
      sha256 "aff91a523780da6e52f60fefc5d76e4e60a9ede7c553e2ad4a306d87ee129cb3"

      def install
        bin.install "checkssl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/checkssl/releases/download/v0.5.1/checkssl_Linux_arm64.tar.gz"
      sha256 "970b8805018a72e55ffaa2e686e3e150f68c3d24e00f895eb9bf33721e0b049d"

      def install
        bin.install "checkssl"
      end
    end
  end

  test do
    system "#{bin}/checkssl checkssl.org"
  end
end
