# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkssl < Formula
  desc "Simple tool to check or monitor TLS/SSL certificates are working."
  homepage "https://www.checkssl.org/"
  version "0.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/checkssl/releases/download/v0.4.4/checkssl_0.4.4_Darwin_arm64.tar.gz"
      sha256 "670633523982f80f6e7422fe1b18d0c386e2cb50f1f3518977decdfb88d9cb50"

      def install
        bin.install "checkssl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/checkssl/releases/download/v0.4.4/checkssl_0.4.4_Darwin_x86_64.tar.gz"
      sha256 "5dd54c8fb984d4caefde84ca1e832987a1e4db1ad3111590efb3931d88a99776"

      def install
        bin.install "checkssl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/checkssl/releases/download/v0.4.4/checkssl_0.4.4_Linux_arm64.tar.gz"
      sha256 "ef9c112e527b1740a02ba9d66f9e114be2c4cd7d1e61e7672962e080b448e2ae"

      def install
        bin.install "checkssl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/checkssl/releases/download/v0.4.4/checkssl_0.4.4_Linux_x86_64.tar.gz"
      sha256 "800f38d783709ecbf71e19b48736f2401731e81c59b03b824724eb28eea209b9"

      def install
        bin.install "checkssl"
      end
    end
  end

  test do
    system "#{bin}/checkssl checkssl.org"
  end
end
