# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sedplus < Formula
  desc "A sed-like stream editor with easier to read syntax"
  homepage "https://checkcli.com/sedplus/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0Darwin_arm64.tar.gz"
      sha256 "08131486f2cb1202fb765ae6fe29da1c523f856c1cebcfa53a22c3f69afafc0b"

      def install
        bin.install "sedplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0Darwin_x86_64.tar.gz"
      sha256 "4fa3a2831d5261c43e7e36e829f7e06150855ebfbf9e6528ef9f8f063307beea"

      def install
        bin.install "sedplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0Linux_arm64.tar.gz"
      sha256 "4d12738758e5c12ad29314c598e8e12ece21596d6d425cdb93c149f3c8486840"

      def install
        bin.install "sedplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0Linux_x86_64.tar.gz"
      sha256 "a429ddd77052b335c1d307aea86fd982b143e42b6d79c9a662260ad5015fcc76"

      def install
        bin.install "sedplus"
      end
    end
  end

  test do
    system "#{bin}/sedplus"
  end
end
