# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sedplus < Formula
  desc "A sed-like stream editor with easier to read syntax"
  homepage "https://checkcli.com/sedplus/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a367e9f9b2dc860982d123c9eca3dade805c8eaa06b9f6dedf8a5e19f879e360"

      def install
        bin.install "sedplus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0_Darwin_arm64.tar.gz"
      sha256 "42b12a424aaf9f86dd39c46679b50f9fe5c3b81a244f7bc07036bbe8e6eaa3f0"

      def install
        bin.install "sedplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0_Linux_arm64.tar.gz"
      sha256 "9673aaaf0775f86f4b8673ab0b95896b1aca2b28657d5aa23201a84fcc223ec4"

      def install
        bin.install "sedplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/sedplus/releases/download/v0.1.0/sedplus_0.1.0_Linux_x86_64.tar.gz"
      sha256 "d55ac20ef7979a88368e82eab07b5ab01865da02e50123a837edd37aef2d2731"

      def install
        bin.install "sedplus"
      end
    end
  end

  test do
    system "#{bin}/sedplus"
  end
end
