# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wifiled < Formula
  desc "Simple tool to control generic wifi led controllers via command line."
  homepage "https://www.wifiled.org/"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.1/wifiled_Darwin_x86_64.tar.gz"
      sha256 "808e5efb3a714756941e41fc85be7e9c1239e0e2081894d01a9cf90b6fa0f2ee"

      def install
        bin.install "wifiled"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.1/wifiled_Darwin_arm64.tar.gz"
      sha256 "13e1deb10b03c4c9a3dde7eefa16d6a6946461633eebf6addb1a5098990d925e"

      def install
        bin.install "wifiled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.1/wifiled_Linux_x86_64.tar.gz"
      sha256 "7aef9473ef88165301e5160e3d10d1302e0ad65dc790e9002895c9febf86b94a"

      def install
        bin.install "wifiled"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.1/wifiled_Linux_arm64.tar.gz"
      sha256 "a180bf3a6fe23f3392ec645cd28b964a0c2ea29cf3c019c808c2548ff78a0d7f"

      def install
        bin.install "wifiled"
      end
    end
  end

  test do
    system "#{bin}/wifiled"
  end
end
