# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wifiled < Formula
  desc "Simple tool to control generic wifi led controllers via command line."
  homepage "https://www.wifiled.org/"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/wifiled/releases/download/v0.3.0/wifiled_0.3.0_Darwin_arm64.tar.gz"
      sha256 "d663b0c8feb4bc4d9fb63f3d9008152d83f1aef7e0f15e09a3417ca4b136b507"

      def install
        bin.install "wifiled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/wifiled/releases/download/v0.3.0/wifiled_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "b5804b52b0ffc24ea4f5005d08383b4b7008a0d3fb446387c279bbc0694e84bd"

      def install
        bin.install "wifiled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/wifiled/releases/download/v0.3.0/wifiled_0.3.0_Linux_arm64.tar.gz"
      sha256 "db36452503826a0217e32b7561c499350cbb4640f550047054ae44cc25f8d33b"

      def install
        bin.install "wifiled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/wifiled/releases/download/v0.3.0/wifiled_0.3.0_Linux_x86_64.tar.gz"
      sha256 "87f60b6d6a81f4c2b5a74ad1bbe235bc31ee876996b36c088f74e005a01b0189"

      def install
        bin.install "wifiled"
      end
    end
  end

  test do
    system "#{bin}/wifiled"
  end
end
