# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wifiled < Formula
  desc "Simple tool to control generic wifi led controllers via command line."
  homepage "https://www.wifiled.org/"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.0/wifiled_Darwin_arm64.tar.gz"
      sha256 "deb8db7acb84d32b641c869087ec9871522dbba281ca5523baaf4a6641193fe1"

      def install
        bin.install "wifiled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.0/wifiled_Darwin_x86_64.tar.gz"
      sha256 "7794b0f1b0424f60a68246c9148205789a818429799f58bea1c2e67f7f917385"

      def install
        bin.install "wifiled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.0/wifiled_Linux_arm64.tar.gz"
      sha256 "b429bac818f6396c507ecd98c93b2b24d074b089423b4986898f78a55c4b41de"

      def install
        bin.install "wifiled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/wifiled/releases/download/v0.4.0/wifiled_Linux_x86_64.tar.gz"
      sha256 "5eb6c8f74a8b71dbeb067b5044c568488ab20a702ac9e401c644ccf5e1f68f2c"

      def install
        bin.install "wifiled"
      end
    end
  end

  test do
    system "#{bin}/wifiled"
  end
end
